### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by ZoeLeBlanc** [jrladd/network_navigator#10]
Changing Graph Customization Box (John)

Force Atlas:
- [x] dropdown for Sizing Nodes (John)
- [x] custom color scheme picker (John)
- [x] toggle directed arrows (Zoe)
- [x] toggle edge weights
- [x] adding linear scales (John)
- [x] collision detection (John)
- [x] click behavior: highlight immediate neighborhood (John)
- [x] scroll to zoom (John)

Arc Diagram:
- [x] dropdown for Sizing Nodes (re-order/positioning on size change) (John)
- [x] custom color scheme picker (John)
- [x] hover on labels (as well as nodes) (Zoe)
- [x] highlight on click and release on doubleclick (Zoe)
- [x] dropdown resort (degree, centrality, alphabetical, etc...) (Zoe)
- [x] look at transitions for reordering/horizontal (John)
- [x] scroll to zoom (John)
- [x] add arrows if directed (Zoe) (we decided not to do this)
- [x] add node border (stroke color)

Matrix:
- [x] dropdown resort (degree, centrality, alphabetical, etc...) (Zoe)
- [x] custom color scheme picker (John)
- [x] Zoom in (on top quandrant - maybe use brush?) *might be push goal* (add your name if you get to it)

Download PNG:
- [x] download on button push (Zoe)

Community Implementation (using https://github.com/upphiminn/jLouvain)
- [x] custom field color (add your name if you get to it) - intended to be a button that you click after initial load

General todos
- [x] headers in textbox (John)
- [x] in-progress when calculating (John using https://css-loader.raphaelfabeni.com/)
- [x] scroll to visualizations and metric after calculating (John)

**Comment by jrladd** [comment]
Quick note from a productive day! I finished the scales and added a checkbox for edge weights. All of that and the size dropdown is pushed to a new `customization` branch. I'll leave the directed arrows for you since you said you were working on it, but I may add the color scheme thing sometime in the next few days.

Once that's done it should be *fairly* simple to copy some of these for the arc diagram as well!

**Comment by ZoeLeBlanc** [comment]
Updates for customization
- [x] Improve click on arc diagram (hover, click on nodes persist, and click on container to release) (Zoe)
- [x] Zoom reset on arc diagram between vertical and horizontal (John)
- [x] Remove scaled_weight weirdness (who ever pushes up first)
- [x] Rethink color picker for matrix (range with D3 using one color towards black and white)

**Comment by ZoeLeBlanc** [comment]
- [x] make graph buttons responsive (Zoe)
- [x] data tables headers don't scroll
- [x] centering button (Zoe)
- [x] download metrics graph (Zoe)
- [x] default metrics to show (John)

**Comment by ZoeLeBlanc** [comment]
- [x] figure out resort symmetry matrix (Zoe)
- [x] disable sort on brush zoom on matrix

**Comment by jrladd** [comment]
- [x] try out community/Louvain (John)
- [x] unify retro design for buttons, etc (Zoe)
- [x] clear matrix brush after zoom (John)
- [x] select filename for table download (John)
- [x] pressing enter in textarea activates function (John)
- [x] add about page
- [x] redo documentation
- [x] code cleanup and documenting the code

**Comment by jrladd** [comment]
@ZoeLeBlanc I looked into the filename issue for the download. My browser does automatically prompt me to rename the file when I click download (opens the "Save as..." dialog), but this is partially because my browser settings always do that.

As far as I can tell, allowing a user to rename a file is handled by the browser and can't necessarily be triggered via Javascript? Datatables lets you [set the filename](https://datatables.net/extensions/buttons/examples/html5/filename.html), but this would just create the same default filename every time a user downloads.

My instinct here is to just skip over this one: there's no easy workaround that I can see, and I'd rather let the browser/individual user handle filenames. (If a user repeatedly downloads the same thing into the same folder, the OS should automatically number it anyway: "NetworkNavigator.csv", "NetworkNavigator (1).csv", "Network Navigator (2).csv," etc. Not ideal, but it won't overwrite data.) Does that sound good to you?

**Comment by ZoeLeBlanc** [comment]
- [ ] Find out if we should add ability to import nodes table for attributes? Also should we let people include other metrics as edge or node attributes? Would impact color of nodes and sizing

**Comment by jrladd** [comment]
- [x] update CSV library
- [x] matrix brush won't clear after restore zoom
